[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12"
# ndarray = "0.15"
num = "0.4"
rand = "0.8"
rayon = "1.8"
regex = "1.10"

[profile.release]
debug = true
